/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as MultiOn from "../index";

export class PaymentRequiredError extends errors.MultiOnError {
    constructor(body: MultiOn.PaymentRequiredResponse) {
        super({
            message: "PaymentRequiredError",
            statusCode: 402,
            body: body,
        });
        Object.setPrototypeOf(this, PaymentRequiredError.prototype);
    }
}
