/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as MultiOn from "../../../../../api/index";
import * as core from "../../../../../core";
import { SessionsStepStreamRequestBrowserParams } from "../../types/SessionsStepStreamRequestBrowserParams";

export const SessionsStepStreamRequest: core.serialization.Schema<
    serializers.SessionsStepStreamRequest.Raw,
    MultiOn.SessionsStepStreamRequest
> = core.serialization.object({
    cmd: core.serialization.string(),
    url: core.serialization.string().optional(),
    browserParams: core.serialization.property("browser_params", SessionsStepStreamRequestBrowserParams.optional()),
    includeScreenshot: core.serialization.property("include_screenshot", core.serialization.boolean().optional()),
});

export declare namespace SessionsStepStreamRequest {
    interface Raw {
        cmd: string;
        url?: string | null;
        browser_params?: SessionsStepStreamRequestBrowserParams.Raw | null;
        include_screenshot?: boolean | null;
    }
}
