/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../../../..";

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface CreateSessionInput {
    /** The URL to create or continue session from. */
    url: string;
    /** Boolean flag to indicate if session to be run locally or in the cloud (Default: False) */
    local?: boolean;
    /** Object containing height and width for the browser screen size. */
    browserParams?: MultiOn.CreateSessionInputBrowserParams;
    includeScreenshot?: boolean;
}
