/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 *
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 *
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 */
export interface RetrieveInput {
    /** A specific natural language instruction on data the agent should extract. */
    cmd: string;
    /** The URL to create or continue session from. */
    url?: string;
    /** Continues the session with session_id if provided. */
    sessionId?: string;
    /** Boolean flag to indicate if session to be run locally or in the cloud (Default: False). If set to true, the session will be run locally via your chrome extension. If set to false, the session will be run in the cloud. */
    local?: boolean;
    /** The starting page number to retrieve data from, where a page is a virtual viewport of the remote browser. If both start_page and end_page are not set, will disable pagination and retrieve the whole page. If end_page is set but not start_page, will retrieve up till end_page. If both are set, will retrieve from start_page to end_page. Useful for large websites with lots of data. */
    startPage?: number;
    /** The ending page number to retrieve data from, where a page is a virtual viewport of the remote browser. If both start_page and end_page are not set, will disable pagination and retrieve the whole page. If start_page is set but not end_page, will retrieve 5 pages starting from start_page. If both are set, will retrieve from start_page to end_page. Useful for large websites with lots of data. */
    endPage?: number;
    /** Flag to include rich JS and ARIA elements in data retrieved. Useful for retrieving image URLs. */
    renderJs?: boolean;
    /** list of comma separated fields you would like extracted from the page */
    fields?: string[];
    /** Format of response data. */
    format?: "json";
    /** Flag to include a screenshot with the response. */
    includeScreenshot?: boolean;
}
