/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 *
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 *
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 */
export interface RetrieveInput {
    /** A specific natural language instruction on data the agent should extract. */
    cmd: string;
    /** Continues the session with session_id if provided. */
    sessionId?: string;
    /** The page number to retrieve data from. where page is a viewport of the browser. */
    pageNumber?: number;
    /** The URL to create or continue session from. */
    url?: string;
    /** list of comma separated fields you would like extracted from the page */
    fields?: string;
    format?: "json";
    /** Flag to include a screenshot with the response. */
    includeScreenshot?: boolean;
}
