/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../../../../index";

/**
 * @example
 *     {
 *         cmd: "cmd",
 *         stream: false
 *     }
 *
 * @example
 *     {
 *         cmd: "cmd",
 *         stream: false
 *     }
 *
 * @example
 *     {
 *         cmd: "cmd",
 *         stream: false
 *     }
 */
export interface SessionsStepRequest {
    /** A specific natural language instruction for the next step. */
    cmd: string;
    /** The URL to create or continue session from. */
    url?: string;
    /** Object containing height and width for the browser screen size. */
    browserParams?: MultiOn.SessionsStepRequestBrowserParams;
    includeScreenshot?: boolean;
}
