/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../../../../index";

/**
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 */
export interface SessionsStepRequest {
    /** A specific natural language instruction for the next step. */
    cmd: string;
    /** The URL to create or continue session from. */
    url?: string;
    /** Object containing height and width for the browser screen size. */
    browserParams?: MultiOn.SessionsStepRequestBrowserParams;
    /** The temperature of model */
    temperature?: number;
    /** The agent id to use for the session. */
    agentId?: string;
    mode?: MultiOn.Mode;
    includeScreenshot?: boolean;
    /** Additional optional parameters for the session. */
    optionalParams?: Record<string, unknown>;
}
