/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../../../../index";

/**
 * @example
 *     {
 *         cmd: "string",
 *         url: "string",
 *         browserParams: {
 *             height: 1.1,
 *             width: 1.1
 *         },
 *         temperature: 1.1,
 *         agentId: "string",
 *         mode: MultiOn.Mode.Fast,
 *         includeScreenshot: true,
 *         optionalParams: {
 *             "string": {
 *                 "key": "value"
 *             }
 *         }
 *     }
 */
export interface SessionsStepStreamRequest {
    /** A specific natural language instruction for the next step. */
    cmd: string;
    /** The URL to create or continue session from. */
    url?: string;
    /** Object containing height and width for the browser screen size. */
    browserParams?: MultiOn.SessionsStepStreamRequestBrowserParams;
    /** The temperature of model */
    temperature?: number;
    /** The agent id to use for the session. */
    agentId?: string;
    mode?: MultiOn.Mode;
    includeScreenshot?: boolean;
    /** Additional optional parameters for the session. */
    optionalParams?: Record<string, unknown>;
}
