/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../../../../index";

/**
 * @example
 *     {
 *         cmd: "string",
 *         url: "string",
 *         stream: true,
 *         browserParams: {
 *             height: 1.1,
 *             width: 1.1
 *         },
 *         temperature: 1.1,
 *         mode: MultiOn.Mode.Fast,
 *         includeScreenshot: true
 *     }
 *
 * @example
 *     {
 *         cmd: "string",
 *         url: "string",
 *         stream: true,
 *         browserParams: {
 *             height: 1.1,
 *             width: 1.1
 *         },
 *         temperature: 1.1,
 *         mode: MultiOn.Mode.Fast,
 *         includeScreenshot: true
 *     }
 */
export interface SessionsStepStreamRequest {
    /** A specific natural language instruction for the next step. */
    cmd: string;
    /** The URL to create or continue session from. */
    url?: string;
    /** Object containing height and width for the browser screen size. */
    browserParams?: MultiOn.SessionsStepStreamRequestBrowserParams;
    /** The temperature of model */
    temperature?: number;
    mode?: MultiOn.Mode;
    includeScreenshot?: boolean;
}
