/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../../../..";

/**
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 */
export interface StepSessionInput {
    /** A specific natural language instruction for the next step. */
    cmd: string;
    /** The URL to create or continue session from. */
    url?: string;
    /** Boolean flag to stream results back to the client (Default: False) */
    stream?: boolean;
    /** Object containing height and width for the browser screen size. */
    browserParams?: MultiOn.StepSessionInputBrowserParams;
    includeScreenshot?: boolean;
}
