/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../index";

export interface BrowseOutput {
    /** The final message or result of the browsing session. */
    message: string;
    /** The final status of the browsing session. One of ["CONTINUE", "ASK_USER", "DONE"] */
    status: string;
    /** The current URL of the session. */
    url: string;
    /** image url of the screenshot taken during the session. */
    screenshot: string;
    /** The unique identifier for the session. */
    sessionId: string;
    /** Additional metadata for the session */
    metadata?: MultiOn.Metadata;
}
