/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The format of the response data. (Default: json)
 */
export type Format = "json" | "markdown";

export const Format = {
    Json: "json",
    Markdown: "markdown",
} as const;
