/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "..";

export interface Message {
    /** A specific natural language instruction for the next step. */
    cmd?: string;
    /** The URL to use for this step. */
    url: string;
    /** Boolean flag to indicate if session to be run locally or in the cloud (Default: False) */
    local?: boolean;
    /** Boolean flag to stream results back to the client (Default: False) */
    stream?: boolean;
    /** Object containing height and width for the browser screen size. */
    browserParams?: MultiOn.MessageBrowserParams;
    includeScreenshot?: boolean;
}
