/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Additional metadata for the session
 */
export interface Metadata {
    /** Number of steps executed to complete browse request. */
    stepCount?: number;
    /** Time taken to process the request in seconds. */
    processingTime?: number;
}
