/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The mode you would like to use for the session. 'fast' or 'standard'
 */
export type Mode = "fast" | "standard";

export const Mode = {
    Fast: "fast",
    Standard: "standard",
} as const;
