/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The mode you would like to use for the session. 'fast', 'standard', or 'ludicrous'.
 */
export type Mode = "fast" | "standard" | "ludicrous";

export const Mode = {
    Fast: "fast",
    Standard: "standard",
    Ludicrous: "ludicrous",
} as const;
