/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RetrieveOutputResponse {
    /** information on a webpage based on a user query */
    message: string;
    /** The last accessed URL during the session. */
    url: string;
    /** image url of the screenshot taken during the session. */
    screenshot?: string;
    /** Dictionary of link available on the web page */
    linkDict: Record<string, string>;
}
