/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RetrieveOutput {
    /** information relating to response */
    message: string;
    /** The last accessed URL during the session. */
    url: string;
    /** image url of the screenshot taken during the session. */
    screenshot?: string;
    /** The unique identifier for the session. */
    sessionId?: string;
    /** The current status of the session. */
    status: string;
    /** Array of data objects, each containing data requested in fields. */
    data: Record<string, unknown>[];
}
