/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../index";

export interface SessionStepSuccess {
    /** The current status of the session. */
    status: string;
    /** A message providing more details about the session status. */
    message: string;
    /** The unique identifier for the session. */
    sessionId: string;
    /** The URL associated with the session. */
    url: string;
    /** image url of the screenshot taken during the session. */
    screenshot: string;
    /** Additional metadata for the step session. */
    metadata?: MultiOn.SessionStepSuccessMetadata;
}
