/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../index";

/**
 * The final delta object for the session.
 */
export interface SessionStreamChunkFinalEventData {
    /** The final delta object for the session. */
    delta: MultiOn.SessionStreamChunkFinalEventDataDelta;
}
