/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../index";

export type SessionStepStreamChunk = MultiOn.SessionStepStreamChunk.Event | MultiOn.SessionStepStreamChunk.FinalEvent;

export declare namespace SessionStepStreamChunk {
    interface Event extends MultiOn.SessionStreamChunkEvent {
        type: "event";
    }

    interface FinalEvent extends MultiOn.SessionStreamChunkFinalEvent {
        type: "final_event";
    }
}
