/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The delta object for the session.
 */
export interface SessionStreamChunkEventDataDelta {
    /** A message providing more details about the session status. */
    content: string;
    /** The URL associated with the session. */
    url: string;
}
