/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "..";

export interface SessionStepSuccessResponse {
    data: MultiOn.SessionStepSuccessResponseData;
    /** The current status of the session. */
    status: string;
}
