/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../index";

export interface SessionStreamChunkFinalEvent {
    /** The final delta object for the session. */
    data: MultiOn.SessionStreamChunkFinalEventData;
    /** The unique identifier for the session. */
    sessionId?: string;
    /** image url of the screenshot taken during the session. */
    screenshot?: string;
}
