/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../index";

/**
 * The delta object for the session.
 */
export interface SessionStreamChunkEventData {
    /** The delta object for the session. */
    delta: MultiOn.SessionStreamChunkEventDataDelta;
}
