/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "..";

export interface SessionCreatedResponse {
    data: MultiOn.SessionCreatedResponseData;
    /** The unique identifier for the session, duplicated for convenience. */
    sessionId: string;
}
