/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Additional metadata for the step session.
 */
export interface SessionStepSuccessMetadata {
    /** The temperature of model */
    temperture?: number;
}
