/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The final delta object for the session.
 */
export interface SessionStreamChunkFinalEventDataDelta {
    /** A message providing more details about the session status. */
    content: string;
    /** The URL associated with the session. */
    url: string;
    /** The final status of the browsing session. One of ["CONTINUE", "ASK_USER", "DONE"] */
    status: string;
}
