/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../index";

export interface SessionStreamChunkEvent {
    /** The delta object for the session. */
    data: MultiOn.SessionStreamChunkEventData;
    /** The unique identifier for the session. */
    sessionId?: string;
}
