/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../index";

export interface ValidationError {
    loc: MultiOn.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
