/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         cmd: "find the top post on hackernews",
 *         url: "https://news.ycombinator.com/"
 *     }
 *
 * @example
 *     {
 *         cmd: "find the top post on hackernews",
 *         url: "https://news.ycombinator.com/"
 *     }
 *
 * @example
 *     {
 *         cmd: "find the top post on hackernews",
 *         url: "https://news.ycombinator.com/"
 *     }
 *
 * @example
 *     {
 *         cmd: "find the top post on hackernews",
 *         url: "https://news.ycombinator.com/"
 *     }
 *
 * @example
 *     {
 *         cmd: "find the top post on hackernews",
 *         url: "https://news.ycombinator.com/"
 *     }
 *
 * @example
 *     {
 *         cmd: "find the top post on hackernews",
 *         url: "https://news.ycombinator.com/"
 *     }
 */
export interface BrowseInput {
    /** A specific natural language instruction for the agent to execute */
    cmd: string;
    /** The URL to start or continue browsing from. (Default: google.com) */
    url?: string;
    /** Boolean flag to indicate if session to be run locally or in the cloud (Default: False) */
    local?: boolean;
    /** Continues the session with session_id if provided. */
    sessionId?: string;
    /** Maximum number of steps to execute. (Default: 20) */
    maxSteps?: number;
    /** Boolean flag to include a screenshot of the final page. */
    includeScreenshot?: boolean;
}
