/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";
import { Metadata } from "./Metadata";

export const BrowseOutput: core.serialization.ObjectSchema<serializers.BrowseOutput.Raw, MultiOn.BrowseOutput> =
    core.serialization.object({
        message: core.serialization.string(),
        status: core.serialization.string(),
        url: core.serialization.string(),
        screenshot: core.serialization.string(),
        sessionId: core.serialization.property("session_id", core.serialization.string()),
        metadata: Metadata.optional(),
    });

export declare namespace BrowseOutput {
    interface Raw {
        message: string;
        status: string;
        url: string;
        screenshot: string;
        session_id: string;
        metadata?: Metadata.Raw | null;
    }
}
