/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";

export const BrowseOutput: core.serialization.ObjectSchema<serializers.BrowseOutput.Raw, MultiOn.BrowseOutput> =
    core.serialization.object({
        message: core.serialization.string(),
        status: core.serialization.string(),
        url: core.serialization.string(),
        pageContent: core.serialization.property("page_content", core.serialization.string()),
        screenshot: core.serialization.string(),
        sessionId: core.serialization.property("session_id", core.serialization.string()),
    });

export declare namespace BrowseOutput {
    interface Raw {
        message: string;
        status: string;
        url: string;
        page_content: string;
        screenshot: string;
        session_id: string;
    }
}
