/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";

export const Format: core.serialization.Schema<serializers.Format.Raw, MultiOn.Format> = core.serialization.enum_([
    "json",
    "markdown",
]);

export declare namespace Format {
    type Raw = "json" | "markdown";
}
