/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";
import { ValidationError } from "./ValidationError";

export const HttpValidationError: core.serialization.ObjectSchema<
    serializers.HttpValidationError.Raw,
    MultiOn.HttpValidationError
> = core.serialization.object({
    detail: core.serialization.list(ValidationError).optional(),
});

export declare namespace HttpValidationError {
    interface Raw {
        detail?: ValidationError.Raw[] | null;
    }
}
