/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";

export const MessageBrowserParams: core.serialization.ObjectSchema<
    serializers.MessageBrowserParams.Raw,
    MultiOn.MessageBrowserParams
> = core.serialization.object({
    height: core.serialization.number().optional(),
    width: core.serialization.number().optional(),
});

export declare namespace MessageBrowserParams {
    interface Raw {
        height?: number | null;
        width?: number | null;
    }
}
