/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";
import { MessageBrowserParams } from "./MessageBrowserParams";

export const Message: core.serialization.ObjectSchema<serializers.Message.Raw, MultiOn.Message> =
    core.serialization.object({
        cmd: core.serialization.string().optional(),
        url: core.serialization.string(),
        stream: core.serialization.boolean().optional(),
        browserParams: core.serialization.property("browser_params", MessageBrowserParams.optional()),
        includeScreenshot: core.serialization.boolean().optional(),
    });

export declare namespace Message {
    interface Raw {
        cmd?: string | null;
        url: string;
        stream?: boolean | null;
        browser_params?: MessageBrowserParams.Raw | null;
        includeScreenshot?: boolean | null;
    }
}
