/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";

export const Mode: core.serialization.Schema<serializers.Mode.Raw, MultiOn.Mode> = core.serialization.enum_([
    "fast",
    "standard",
    "ludicrous",
]);

export declare namespace Mode {
    type Raw = "fast" | "standard" | "ludicrous";
}
