/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";

export const OptionalParams: core.serialization.ObjectSchema<serializers.OptionalParams.Raw, MultiOn.OptionalParams> =
    core.serialization.object({
        temperture: core.serialization.number().optional(),
    });

export declare namespace OptionalParams {
    interface Raw {
        temperture?: number | null;
    }
}
