/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";

export const PaymentRequiredResponse: core.serialization.ObjectSchema<
    serializers.PaymentRequiredResponse.Raw,
    MultiOn.PaymentRequiredResponse
> = core.serialization.object({
    statusCode: core.serialization.number().optional(),
    error: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace PaymentRequiredResponse {
    interface Raw {
        statusCode?: number | null;
        error?: string | null;
        message?: string | null;
    }
}
