/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";

export const RemoteValue: core.serialization.ObjectSchema<serializers.RemoteValue.Raw, MultiOn.RemoteValue> =
    core.serialization.object({
        value: core.serialization.boolean(),
    });

export declare namespace RemoteValue {
    interface Raw {
        value: boolean;
    }
}
