/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";

export const SessionStreamChunkEventDataDelta: core.serialization.ObjectSchema<
    serializers.SessionStreamChunkEventDataDelta.Raw,
    MultiOn.SessionStreamChunkEventDataDelta
> = core.serialization.object({
    content: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace SessionStreamChunkEventDataDelta {
    interface Raw {
        content: string;
        url: string;
    }
}
