/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";

export const SessionStreamChunkFinalEventDataDelta: core.serialization.ObjectSchema<
    serializers.SessionStreamChunkFinalEventDataDelta.Raw,
    MultiOn.SessionStreamChunkFinalEventDataDelta
> = core.serialization.object({
    content: core.serialization.string(),
    url: core.serialization.string(),
    status: core.serialization.string(),
});

export declare namespace SessionStreamChunkFinalEventDataDelta {
    interface Raw {
        content: string;
        url: string;
        status: string;
    }
}
