/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";
import { SessionStepSuccessResponse } from "./SessionStepSuccessResponse";

export const SessionStepSuccess: core.serialization.ObjectSchema<
    serializers.SessionStepSuccess.Raw,
    MultiOn.SessionStepSuccess
> = core.serialization.object({
    response: SessionStepSuccessResponse,
});

export declare namespace SessionStepSuccess {
    interface Raw {
        response: SessionStepSuccessResponse.Raw;
    }
}
