/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";

export const SessionStepSuccessMetadata: core.serialization.ObjectSchema<
    serializers.SessionStepSuccessMetadata.Raw,
    MultiOn.SessionStepSuccessMetadata
> = core.serialization.object({
    temperature: core.serialization.number().optional(),
});

export declare namespace SessionStepSuccessMetadata {
    interface Raw {
        temperature?: number | null;
    }
}
