/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";
import { SessionStreamChunkFinalEventData } from "./SessionStreamChunkFinalEventData";

export const SessionStreamChunkFinalEvent: core.serialization.ObjectSchema<
    serializers.SessionStreamChunkFinalEvent.Raw,
    MultiOn.SessionStreamChunkFinalEvent
> = core.serialization.object({
    data: SessionStreamChunkFinalEventData,
    sessionId: core.serialization.property("session_id", core.serialization.string().optional()),
    screenshot: core.serialization.string().optional(),
});

export declare namespace SessionStreamChunkFinalEvent {
    interface Raw {
        data: SessionStreamChunkFinalEventData.Raw;
        session_id?: string | null;
        screenshot?: string | null;
    }
}
