/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";
import { SessionCreatedResponseData } from "./SessionCreatedResponseData";

export const SessionCreatedResponse: core.serialization.ObjectSchema<
    serializers.SessionCreatedResponse.Raw,
    MultiOn.SessionCreatedResponse
> = core.serialization.object({
    data: SessionCreatedResponseData,
    sessionId: core.serialization.property("session_id", core.serialization.string()),
});

export declare namespace SessionCreatedResponse {
    interface Raw {
        data: SessionCreatedResponseData.Raw;
        session_id: string;
    }
}
