/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";
import { SessionStreamChunkFinalEventDataDelta } from "./SessionStreamChunkFinalEventDataDelta";

export const SessionStreamChunkFinalEventData: core.serialization.ObjectSchema<
    serializers.SessionStreamChunkFinalEventData.Raw,
    MultiOn.SessionStreamChunkFinalEventData
> = core.serialization.object({
    delta: SessionStreamChunkFinalEventDataDelta,
});

export declare namespace SessionStreamChunkFinalEventData {
    interface Raw {
        delta: SessionStreamChunkFinalEventDataDelta.Raw;
    }
}
