/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";
import { SessionStepStreamChunk } from "./SessionStepStreamChunk";

export const SessionStepStream: core.serialization.Schema<
    serializers.SessionStepStream.Raw,
    MultiOn.SessionStepStream
> = core.serialization.list(SessionStepStreamChunk);

export declare namespace SessionStepStream {
    type Raw = SessionStepStreamChunk.Raw[];
}
