/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";
import { SessionStreamChunkEventDataDelta } from "./SessionStreamChunkEventDataDelta";

export const SessionStreamChunkEventData: core.serialization.ObjectSchema<
    serializers.SessionStreamChunkEventData.Raw,
    MultiOn.SessionStreamChunkEventData
> = core.serialization.object({
    delta: SessionStreamChunkEventDataDelta,
});

export declare namespace SessionStreamChunkEventData {
    interface Raw {
        delta: SessionStreamChunkEventDataDelta.Raw;
    }
}
