/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";
import { SessionCreatedResponse } from "./SessionCreatedResponse";

export const SessionCreated: core.serialization.ObjectSchema<serializers.SessionCreated.Raw, MultiOn.SessionCreated> =
    core.serialization.object({
        response: SessionCreatedResponse,
    });

export declare namespace SessionCreated {
    interface Raw {
        response: SessionCreatedResponse.Raw;
    }
}
