/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MultiOn from "../../api";
import * as core from "../../core";

export const SessionCreatedResponseData: core.serialization.ObjectSchema<
    serializers.SessionCreatedResponseData.Raw,
    MultiOn.SessionCreatedResponseData
> = core.serialization.object({
    status: core.serialization.string(),
    message: core.serialization.string(),
    sessionId: core.serialization.property("session_id", core.serialization.string()),
    url: core.serialization.string(),
    screenshot: core.serialization.string(),
});

export declare namespace SessionCreatedResponseData {
    interface Raw {
        status: string;
        message: string;
        session_id: string;
        url: string;
        screenshot: string;
    }
}
