/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MultiOn from "../../api/index";
import * as core from "../../core";

export const UnauthorizedResponse: core.serialization.ObjectSchema<
    serializers.UnauthorizedResponse.Raw,
    MultiOn.UnauthorizedResponse
> = core.serialization.object({
    statusCode: core.serialization.number().optional(),
    error: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace UnauthorizedResponse {
    interface Raw {
        statusCode?: number | null;
        error?: string | null;
        message?: string | null;
    }
}
