/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MultiOn from "../../../../api/index";
import * as core from "../../../../core";

export const SessionsCloseResponse: core.serialization.ObjectSchema<
    serializers.SessionsCloseResponse.Raw,
    MultiOn.SessionsCloseResponse
> = core.serialization.object({
    status: core.serialization.string(),
    sessionId: core.serialization.property("session_id", core.serialization.string()),
});

export declare namespace SessionsCloseResponse {
    interface Raw {
        status: string;
        session_id: string;
    }
}
