/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";
import { SessionsRetrieveScreenshotResponseResponse } from "./SessionsRetrieveScreenshotResponseResponse";

export const SessionsRetrieveScreenshotResponse: core.serialization.ObjectSchema<
    serializers.SessionsRetrieveScreenshotResponse.Raw,
    MultiOn.SessionsRetrieveScreenshotResponse
> = core.serialization.object({
    response: SessionsRetrieveScreenshotResponseResponse,
});

export declare namespace SessionsRetrieveScreenshotResponse {
    interface Raw {
        response: SessionsRetrieveScreenshotResponseResponse.Raw;
    }
}
