/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";

export const SessionsScreenshotResponse: core.serialization.ObjectSchema<
    serializers.SessionsScreenshotResponse.Raw,
    MultiOn.SessionsScreenshotResponse
> = core.serialization.object({
    screenshot: core.serialization.string(),
});

export declare namespace SessionsScreenshotResponse {
    interface Raw {
        screenshot: string;
    }
}
