/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";
import { SessionsListResponseResponse } from "./SessionsListResponseResponse";

export const SessionsListResponse: core.serialization.ObjectSchema<
    serializers.SessionsListResponse.Raw,
    MultiOn.SessionsListResponse
> = core.serialization.object({
    response: SessionsListResponseResponse,
});

export declare namespace SessionsListResponse {
    interface Raw {
        response: SessionsListResponseResponse.Raw;
    }
}
