/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MultiOn from "../../../../api/index";
import * as core from "../../../../core";

export const SessionsStepStreamRequestBrowserParams: core.serialization.ObjectSchema<
    serializers.SessionsStepStreamRequestBrowserParams.Raw,
    MultiOn.SessionsStepStreamRequestBrowserParams
> = core.serialization.object({
    height: core.serialization.number().optional(),
    width: core.serialization.number().optional(),
});

export declare namespace SessionsStepStreamRequestBrowserParams {
    interface Raw {
        height?: number | null;
        width?: number | null;
    }
}
