/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";

export const SessionsListResponseResponse: core.serialization.ObjectSchema<
    serializers.SessionsListResponseResponse.Raw,
    MultiOn.SessionsListResponseResponse
> = core.serialization.object({
    status: core.serialization.string(),
    length: core.serialization.number(),
    sessionIds: core.serialization.property("session_ids", core.serialization.list(core.serialization.string())),
});

export declare namespace SessionsListResponseResponse {
    interface Raw {
        status: string;
        length: number;
        session_ids: string[];
    }
}
