/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";

export const SessionsCloneResponseResponse: core.serialization.ObjectSchema<
    serializers.SessionsCloneResponseResponse.Raw,
    MultiOn.SessionsCloneResponseResponse
> = core.serialization.object({
    data: core.serialization.string(),
    sessionId: core.serialization.property("session_id", core.serialization.string()),
});

export declare namespace SessionsCloneResponseResponse {
    interface Raw {
        data: string;
        session_id: string;
    }
}
