/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";

export const SessionsRetrieveScreenshotResponseResponse: core.serialization.ObjectSchema<
    serializers.SessionsRetrieveScreenshotResponseResponse.Raw,
    MultiOn.SessionsRetrieveScreenshotResponseResponse
> = core.serialization.object({
    message: core.serialization.string(),
    sessionId: core.serialization.property("session_id", core.serialization.string()),
    screenshot: core.serialization.string(),
});

export declare namespace SessionsRetrieveScreenshotResponseResponse {
    interface Raw {
        message: string;
        session_id: string;
        screenshot: string;
    }
}
