/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MultiOn from "../../../../api/index";
import * as core from "../../../../core";

export const SessionsListResponse: core.serialization.ObjectSchema<
    serializers.SessionsListResponse.Raw,
    MultiOn.SessionsListResponse
> = core.serialization.object({
    sessionIds: core.serialization.property("session_ids", core.serialization.list(core.serialization.string())),
});

export declare namespace SessionsListResponse {
    interface Raw {
        session_ids: string[];
    }
}
