/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";

export const SessionsCloneResponse: core.serialization.ObjectSchema<
    serializers.SessionsCloneResponse.Raw,
    MultiOn.SessionsCloneResponse
> = core.serialization.object({
    status: core.serialization.string(),
    sessionId: core.serialization.property("session_id", core.serialization.string()),
});

export declare namespace SessionsCloneResponse {
    interface Raw {
        status: string;
        session_id: string;
    }
}
