/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";
import { SessionsCloneResponseResponse } from "./SessionsCloneResponseResponse";

export const SessionsCloneResponse: core.serialization.ObjectSchema<
    serializers.SessionsCloneResponse.Raw,
    MultiOn.SessionsCloneResponse
> = core.serialization.object({
    response: SessionsCloneResponseResponse,
});

export declare namespace SessionsCloneResponse {
    interface Raw {
        response: SessionsCloneResponseResponse.Raw;
    }
}
