/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";

export const SessionsRetrieveScreenshotResponse: core.serialization.ObjectSchema<
    serializers.SessionsRetrieveScreenshotResponse.Raw,
    MultiOn.SessionsRetrieveScreenshotResponse
> = core.serialization.object({
    screenshot: core.serialization.string(),
});

export declare namespace SessionsRetrieveScreenshotResponse {
    interface Raw {
        screenshot: string;
    }
}
