/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as MultiOn from "../../../../api";
import * as core from "../../../../core";

export const StepSessionInputBrowserParams: core.serialization.ObjectSchema<
    serializers.StepSessionInputBrowserParams.Raw,
    MultiOn.StepSessionInputBrowserParams
> = core.serialization.object({
    height: core.serialization.number().optional(),
    width: core.serialization.number().optional(),
});

export declare namespace StepSessionInputBrowserParams {
    interface Raw {
        height?: number | null;
        width?: number | null;
    }
}
