/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const MultiOnEnvironment = {
    Default: "https://api.multion.ai/v1/web",
} as const;

export type MultiOnEnvironment = typeof MultiOnEnvironment.Default;
