/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SessionsCloneResponseResponse {
    /** response data */
    data: string;
    /** The unique identifier for the session, duplicated for convenience. */
    sessionId: string;
}
