/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MultiOn from "../../..";

export interface SessionsCloneResponse {
    response: MultiOn.SessionsCloneResponseResponse;
}
