/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SessionsListResponseResponse {
    /** The current status of the session. */
    status: string;
    /** The number of sessions. */
    length: number;
    /** The list of session IDs. */
    sessionIds: string[];
}
