/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SessionsScreenshotResponse {
    /** Image url of the screenshot taken during the session. */
    screenshot: string;
}
