/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SessionsRetrieveScreenshotResponse {
    /** A base64 encoded string of the screenshot, empty if not available. */
    screenshot: string;
}
