/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object containing height and width for the browser screen size.
 */
export interface StepSessionInputBrowserParams {
    height?: number;
    width?: number;
}
